### ISSUE TITLE
PlayerVault Feature Request

### ISSUE THREAD

**Issue by EpicPinkCreeper** [alexbgameson/3.0.0Alpha9-PocketMine-Plugins#3]
Can you add an option in the configuration to turn permissions off for normal/non-op players? This way we can add the permissions to groups (with the PurePerms plugin) so the player vaults can only work in certain worlds or for players of certain ranks.

**Comment by nikipuh** [comment]
Use Worldprotect and block the commands :)

**Comment by EpicPinkCreeper** [comment]
Thank you! :)
